### ISSUE TITLE
client.library.get_file(item_id) is hanging?

### ISSUE THREAD

**Issue by hobleyd** [radityaharya/jellyfinapi#2]
Hi,

I am playing around with your API - thanks for this - once I got my head around it, it is easy to use.

I have searched for a media_item successfully:
```
>>> movies = client.search.get('Movie Name')
>>> movies.search_hints[0].item_id
'6cbc654c613d65935046f18f4e1b4907'
>>> client.library.get_file('6cbc654c613d65935046f18f4e1b4907')
```

but the last call never responds. Any idea how I could debug this please?

**Comment by radityaharya** [comment]
Hi, the [`get_file`](https://github.com/radityaharya/jellyfinapi/blob/master/jellyfinapi/controllers/library_controller.py#L495) method sends a request to [/Items/{itemId}/File](https://api.jellyfin.org/#tag/Library/operation/GetFile) and returns a binary file stream of said itemId, depending on the size of the item it probably will take a while.

**Comment by hobleyd** [comment]
Ah - that makes sense. Is there an API to the the path of the media item at all? I am working on syncing my read statuses between a couple of different systems and it is the only sure way to match the media given different metadata scanning algorithms between systems...

**Comment by radityaharya** [comment]
If you want to get the filepath of the item try using [`get_items`](https://github.com/radityaharya/jellyfinapi/blob/master/doc/controllers/items.md) if that doesn't work, try adding `PATH` enum in the fields arg 

[item-fields-enum](https://github.com/radityaharya/jellyfinapi/blob/master/doc/models/item-fields-enum.md)
[api reference](https://api.jellyfin.org/#tag/Items/operation/GetItems)

**Comment by hobleyd** [comment]
That worked beautifully. Thanks for the help.
